In [15]:
import pandas as pd

In [16]:
url = "dataset/UPDOWND.csv"
pd.read_csv(url)

                                                                                             MCD;S&P;DJ;Wendy;YUM;Starbuck;Coca;Wheat;Oil;Commodity;sugar;Volatilty;War
1;-0 0028;-0 0008;-0 0033;0  0013;-0 0034;0  0023;-0 0207;-0 0040;-0 0044;0  0200;-0 0990;1                                                  0
0;-0 0031;-0 0041;-0 0167;-0 0118;-0 0004;-0 0015;0  0005;0  0164;0  0143;0  0046;0  1485;1                                                  0
     0014;-0 0077;-0 0257;-0 0025;-0 0104;0  0003;0  0146;-0 0054;-0 0018;-0 0095;-0 5238;1                                                  0
0;0  0032;0  0068;0  0269;0  0004;-0 0102;-0 0046;0  0032;-0 0075;0  0020;0  0133;1  1193;1                                                  0
     0089;0  0103;0  0092;-0 0057;0  0110;0  0086;-0 0136;-0 0214;0  0012;0  0060;-0 0374;1                                                  0
...                                                                                                                                        ...
1;0  0021;0  0064;0  0122;-0 0009;0  0003;0  0065;-0 0064;0  0158;0  0041;0  0039;-0 0175;0                                                  0
             0015;0  0017;0  0036;0  0008;-0 0084;-0 0005;-0 0058;0  0036;0  0233;0  0128;0                                                  0
0;0  0000;-0 0030;0  0073;-0 0040;0  0042;-0 0032;0  0151;-0 0019;0  0021;-0 0190;0  0137;0                                                  0
     0116;0  0127;-0 0039;0  0077;-0 0051;-0 0030;0  0027;0  0161;0  0072;-0 0008;-0 0300;0                                                  0
     0067;0  0082;0  0119;0  0068;0  0051;0  0060;0  0109;0  0241;-0 0049;0  0112;-0 0640;0                                                  0

[1257 rows x 1 columns]

In [10]:

dados = pd.read_csv(url, sep=";")
dados

,MCD,S&P,DJ,Wendy,YUM,Starbuck,Coca,Wheat,Oil,Commodity,sugar,Volatilty,War
0,1,"-0,0028","-0,0008","-0,0033","0,0013","-0,0034","0,0023","-0,0207","-0,0040","-0,0044","0,0200","-0,0990","1,0000"
1,0,"-0,0031","-0,0041","-0,0167","-0,0118","-0,0004","-0,0015","0,0005","0,0164","0,0143","0,0046","0,1485","1,0000"
2,0,"-0,0014","-0,0077","-0,0257","-0,0025","-0,0104","0,0003","0,0146","-0,0054","-0,0018","-0,0095","-0,5238","1,0000"
3,0,"0,0032","0,0068","0,0269","0,0004","-0,0102","-0,0046","0,0032","-0,0075","0,0020","0,0133","1,1193","1,0000"
4,0,"0,0089","0,0103","0,0092","-0,0057","0,0110","0,0086","-0,0136","-0,0214","0,0012","0,0060","-0,0374","1,0000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1252,1,"0,0021","0,0064","0,0122","-0,0009","0,0003","0,0065","-0,0064","0,0158","0,0041","0,0039","-0,0175","0,0000"
1253,1,"0,0021","0,0015","0,0017","0,0036","0,0008","-0,0084","-0,0005","-0,0058","0,0036","0,0233","0,0128","0,0000"
1254,0,"0,0000","-0,0030","0,0073","-0,0040","0,0042","-0,0032","0,0151","-0,0019","0,0021","-0,0190","0,0137","0,0000"
1255,0,"0,0116","0,0127","-0,0039","0,0077","-0,0051","-0,0030","0,0027","0,0161","0,0072","-0,0008","-0,0300","0,0000"
1256,0,"0,0067","0,0082","0,0119","0,0068","0,0051","0,0060","0,0109","0,0241","-0,0049","0,0112","-0,0640","0,0000"

In [12]:
dados.head(25)

,MCD,S&P,DJ,Wendy,YUM,Starbuck,Coca,Wheat,Oil,Commodity,sugar,Volatilty,War
0,1,"-0,0028","-0,0008","-0,0033","0,0013","-0,0034","0,0023","-0,0207","-0,0040","-0,0044","0,0200","-0,0990","1,0000"
1,0,"-0,0031","-0,0041","-0,0167","-0,0118","-0,0004","-0,0015","0,0005","0,0164","0,0143","0,0046","0,1485","1,0000"
2,0,"-0,0014","-0,0077","-0,0257","-0,0025","-0,0104","0,0003","0,0146","-0,0054","-0,0018","-0,0095","-0,5238","1,0000"
3,0,"0,0032","0,0068","0,0269","0,0004","-0,0102","-0,0046","0,0032","-0,0075","0,0020","0,0133","1,1193","1,0000"
4,0,"0,0089","0,0103","0,0092","-0,0057","0,0110","0,0086","-0,0136","-0,0214","0,0012","0,0060","-0,0374","1,0000"
5,1,"0,0056","0,0083","0,0099","0,0075","0,0064","0,0017","0,0180","0,0091","-0,0093","-0,0235","-0,0336","1,0000"
6,1,"0,0063","0,0020","-0,0065","-0,0042","0,0099","0,0042","0,0270","0,0207","0,0038","0,0018","0,0487","1,0000"
7,0,"-0,0065","-0,0049","0,0044","-0,0023","-0,0168","-0,0102","0,0173","-0,0027","0,0111","0,0161","0,0073","1,0000"
8,0,"-0,0029","-0,0035","-0,0146","-0,0087","0,0005","-0,0101","-0,0240","0,0193","0,0040","-0,0073","-0,0135","1,0000"
9,0,"-0,0019","0,0010","0,0071","-0,0169","-0,0085","0,0102","-0,0061","0,0278","0,0099","0,0018","-0,0701","1,0000"
10,0,"0,0112","0,0061","-0,0033","0,0047","0,0036","0,0043","-0,0037","-0,0047","0,0034","-0,0027","-0,0252","1,0000"
11,0,"-0,0011","0,0012","0,0016","0,0037","0,0111","0,0121","0,0204","-0,0010","0,0121","0,0378","-0,0032","1,0000"
12,1,"-0,0065","-0,0018","0,0033","-0,0058","0,0012","0,0013","0,0115","-0,0117","-0,0086","-0,0061","-0,1713","1,0000"
13,1,"0,0103","0,0034","-0,0150","0,0059","-0,0076","-0,0018","-0,0010","-0,0025","0,0104","-0,0079","-0,0033","1,0000"
14,0,"0,0051","0,0020","0,0108","0,0061","0,0047","0,0005","-0,0449","0,0125","0,0096","0,0278","-0,0568","1,0000"
15,1,"-0,0102","-0,0104","0,0082","0,0011","-0,0134","-0,0048","-0,0315","-0,0075","-0,0087","0,0131","0,3458","1,0000"
16,1,"-0,0012","-0,0025","0,0150","0,0082","-0,0075","0,0047","0,0063","-0,0154","0,0040","-0,0232","0,0370","1,0000"
17,1,"0,0080","0,0023","-0,0050","-0,0072","-0,0183","-0,0082","-0,0303","0,0219","-0,0009","-0,0660","-0,0324","1,0000"
18,0,"0,0052","0,0012","-0,0184","-0,0013","0,0204","-0,0063","0,0114","-0,0036","-0,0007","-0,0596","-0,1763","1,0000"
19,0,"-0,0017","-0,0006","0,0188","0,0114","-0,0120","0,0010","-0,0256","-0,0042","-0,0078","0,0071","0,2181","1,0000"
20,1,"0,0017","-0,0025","-0,0049","-0,0074","-0,0016","-0,0061","0,0152","0,0166","0,0028","0,0298","-0,0323","1,0000"
21,0,"-0,0038","-0,0016","-0,0049","-0,0019","-0,0140","-0,0080","0,0065","0,0143","0,0094","0,0234","0,0396","1,0000"
22,0,"0,0003","0,0016","0,0178","0,0072","-0,0017","0,0008","-0,0167","-0,0270","-0,0059","-0,0092","-0,1361","1,0000"
23,1,"0,0211","0,0118","0,0056","0,0155","0,0080","-0,0015","0,0000","0,0090","-0,0024","0,0026","-0,0066","1,0000"
24,1,"0,0013","0,0013","-0,0056","0,0096","0,0167","0,0089","0,0009","-0,0035","0,0098","0,0009","-0,0224","1,0000"

In [13]:
dados.tail(20)

,MCD,S&P,DJ,Wendy,YUM,Starbuck,Coca,Wheat,Oil,Commodity,sugar,Volatilty,War
1237,0,"0,0047","0,0031","0,0005","0,0062","0,0044","0,0088","-0,0190","0,0032","-0,0044","-0,0514","-0,0251","0,0000"
1238,0,"-0,0004","-0,0051","0,0141","0,0011","0,0094","-0,0029","0,0006","-0,0293","-0,0059","-0,0081","0,0045","0,0000"
1239,1,"-0,0022","-0,0022","-0,0064","0,0041","0,0053","-0,0048","0,0058","-0,0103","-0,0049","-0,0252","0,0417","0,0000"
1240,1,"0,0088","0,0055","-0,0043","-0,0025","0,0078","0,0171","-0,0148","-0,0062","-0,0036","-0,0016","-0,0099","0,0000"
1241,1,"0,0010","-0,0018","-0,0111","-0,0014","-0,0087","-0,0017","0,0069","0,0091","-0,0020","0,0128","0,0340","0,0000"
1242,0,"0,0016","0,0042","0,0059","0,0179","0,0125","0,0042","-0,0191","0,0266","-0,0005","-0,0172","-0,0395","0,0000"
1243,1,"-0,0023","-0,0001","0,0086","-0,0013","-0,0077","0,0070","-0,0062","0,0038","-0,0023","0,0332","0,0000","0,0000"
1244,0,"0,0005","0,0026","0,0032","-0,0001","-0,0060","-0,0011","0,0045","-0,0045","-0,0048","-0,0128","-0,0068","0,0000"
1245,0,"-0,0006","-0,0010","0,0070","0,0024","-0,0064","0,0056","-0,0316","0,0103","-0,0033","-0,0118","-0,0105","0,0000"
1246,1,"0,0066","0,0103","0,0027","0,0063","0,0103","0,0006","-0,0108","-0,0077","0,0048","-0,0086","-0,0623","0,0000"
1247,1,"0,0000","-0,0005","0,0222","0,0073","0,0052","0,0015","0,0087","0,0049","-0,0028","0,0087","-0,0049","0,0000"
1248,0,"0,0035","0,0003","0,0000","0,0056","0,0048","-0,0006","0,0055","-0,0159","0,0041","-0,0117","-0,0433","0,0000"
1249,0,"-0,0061","-0,0072","-0,0022","-0,0011","-0,0011","0,0026","-0,0033","0,0098","-0,0023","0,0023","0,0417","0,0000"
1250,1,"0,0010","-0,0032","-0,0121","-0,0037","0,0023","0,0017","-0,0124","-0,0065","0,0005","0,0167","0,0580","0,0000"
1251,0,"0,0046","0,0015","0,0027","-0,0049","0,0091","-0,0002","-0,0053","0,0209","0,0008","-0,0149","-0,0292","0,0000"
1252,1,"0,0021","0,0064","0,0122","-0,0009","0,0003","0,0065","-0,0064","0,0158","0,0041","0,0039","-0,0175","0,0000"
1253,1,"0,0021","0,0015","0,0017","0,0036","0,0008","-0,0084","-0,0005","-0,0058","0,0036","0,0233","0,0128","0,0000"
1254,0,"0,0000","-0,0030","0,0073","-0,0040","0,0042","-0,0032","0,0151","-0,0019","0,0021","-0,0190","0,0137","0,0000"
1255,0,"0,0116","0,0127","-0,0039","0,0077","-0,0051","-0,0030","0,0027","0,0161","0,0072","-0,0008","-0,0300","0,0000"
1256,0,"0,0067","0,0082","0,0119","0,0068","0,0051","0,0060","0,0109","0,0241","-0,0049","0,0112","-0,0640","0,0000"

In [14]:
type(dados)

pandas.core.frame.DataFrame