# Imobiliária Aluga Rápido

In [1]:
import pandas as pd

### Importar Dados

In [2]:
url = "dataset/aluguel.csv"
pd.read_csv(url)

      Tipo;Bairro;Quartos;Vagas;Suites;Area;Valor;Condominio;IPTU
0              Quitinete;Copacabana;1;0;0;40;1700;500;60
1                  Casa;Jardim Botânico;2;0;1;100;7000;;
2      Conjunto Comercial/Sala;Barra da Tijuca;0;4;0;...
3                 Apartamento;Centro;1;0;0;15;800;390;20
4             Apartamento;Higienópolis;1;0;0;48;800;230;
...                                                  ...
32955               Quitinete;Centro;0;0;0;27;800;350;25
32956       Apartamento;Jacarepaguá;3;1;2;78;1800;800;40
32957  Apartamento;São Francisco Xavier;2;1;0;48;1400...
32958              Apartamento;Leblon;2;0;0;70;3000;760;
32959  Conjunto Comercial/Sala;Centro;0;0;0;250;6500;...

[32960 rows x 1 columns]

### Separando por ";"

In [2]:
url = "dataset/aluguel.csv"
dados = pd.read_csv(url, sep=";")
dados

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/aluguel.csv'

# Visualizando Dados
### Algumas Linhas

In [13]:
dados.head(25)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0
10,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
11,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
12,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
13,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
14,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
15,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
16,Prédio Inteiro,Botafogo,0,0,0,536,28000.0,NaN,3563.0
17,Flat,Botafogo,3,1,1,80,3800.0,1040.0,NaN
18,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
19,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
20,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
21,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
22,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
23,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
24,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN

### Visualizando a parte inferior do DataFrame

In [10]:
dados.tail(20)

NameError: name 'dados' is not defined

### Mostrar o Tipo

In [16]:
type(dados)

pandas.core.frame.DataFrame